lobby_spawn_point: 0.5 118 0.5
lobby_pos1: 14 104 -18
lobby_pos2: -20 134 20
min_players: 2
max_players: 16
start_countdown_timer: 30
spawn_points:
    aqua: 0.5 63 -77.5
    pink: -78.5 63 1.5 -90 0
    red: 0.5 63 80.5 180 0
    blue: 79.5 63 1.5 90 0
drop_points:
    iron_gold:
        - 82.5 63.5 1.5
        - 0.5 63.5 -80.5
        - -81.5 63.5 1.5
        - 0.5 63.5 83.5
    diamond:
        - 44.5 65 -45.5
        - -46.5 65 -42.5
        - -43.5 65 48.5
        - 47.5 65 45.5
    emerald:
        - 0.5 66 1.5
        - 0.5 85 1.5
item_shops:
    - 6.5 63.0 -78.0 90 0
    - -79.0 63.00 -4.5 0 0
    - -5.5 63.00 81.0 -90 0
    - 80.0 63.00 7.5 180 0
